wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.4
    start_time: 1646050863
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      3:
      - 13
      4: 3.7.4
      5: 0.12.10
      8:
      - 5
